### ISSUE TITLE
HTML/CSS のTips

### ISSUE THREAD

**Issue by Haramaki0326** [Haramaki0326/StudyToDo#68]

**Comment by Haramaki0326** [comment]
# 垂直方向の中央寄せについて
## 参考
- [CSSで要素を上下や左右から中央寄せする7つの方法](https://www.granfairs.com/blog/staff/centering-by-css)
- [上下中央揃えのCSSまとめ Flexboxがたった3行で最も手軽](https://ics.media/entry/17522/)

## 概要
``` css
.container {
  display: flex;
  justify-content: center;  // 縦方向
  align-items: center;      // 横方向
}
```
