### ISSUE TITLE
フロントエンドの環境構築について（npm, ESLint, Prettier, React, TypeScript, husky, lint-staged）

### ISSUE THREAD

**Issue by Haramaki0326** [Haramaki0326/StudyToDo#73]

**Comment by Haramaki0326** [comment]
# 1. `create-react-app`
`npx create-react-app プロジェクト名 --template typescript`
まずはTSベースのReact環境をnpxでインストール

# 2. ESLintの設定
## 2.1 ESLintとは
- JavaScript/TypeScript 向けの Lint ツール（静的解析ツール）
- プロジェクト内のソースコードに対して `eslint` コマンドを実行することで、コーディングルールに従っていない部分や、不具合の原因になりそうな部分を検出

## 2.2 インストール
`$ npm install eslint -D`

## 2.3 初期設定
- `npx eslint --init` でY/N形式で設定が可能
- スタイルをAirbnbかStandardにするのが吉
- YAMLはコメントの書けるJSONなのでどちらも選べるなら前者の方がいい

## 2.4 実行
- ESLintの実行は`eslint`コマンド
  - `.ts`,`.tsx`を対象にするには`--ext ts,tsx`オプションを指定
  - 上記`--ext`オプションを利用せずに、`.eslintrc`の`overrides`にファイルを指定するやり方でもよい
    - 詳細は`2.5 エラー対処 対応後の.eslintrc.yml`を参照
    - 参考：[ESLint v7.0.0 の変更点まとめ - Qiita](https://qiita.com/mysticatea/items/0931a7d910fcb91733ee#overrides-%E8%A8%AD%E5%AE%9A%E3%81%AB%E4%B8%80%E8%87%B4%E3%81%99%E3%82%8B%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E8%87%AA%E5%8B%95%E7%9A%84%E3%81%AB%E3%83%AA%E3%83%B3%E3%83%88%E5%AF%BE%E8%B1%A1%E3%81%AB%E3%81%97%E3%81%BE%E3%81%99)

 ``` yml
overrides:
  - files: ['*.ts', '*.tsx']
```
   

## 2.5 エラー対処
### 対応後の`.eslintrc.yml`

``` yml
env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
overrides:
  - files: ['*.ts', '*.tsx']
rules:
  import/extensions:
    - error
    - ts: never
      tsx: never
      js: never
      jsx: never
  react/jsx-filename-extension:
    - error
    - extensions:
      - ".jsx"
      - ".tsx"
settings:
  import/resolver:
    node:
      extensions: [.ts, .tsx, .js, .jsx]
```

### 変更1
- エラー内容：`'test' is not defined `

``` yml
env:
  browser: true
  es2021: true
+  jest: true
```

### 変更2
- エラー内容：`JSX not allowed in files with extension '.tsx'`
- エラー内容：`Unable to resolve path to module './App'  `
- Airbnb スタイルの import 設定 が .js ファイルを前提としており、拡張子を省略して .ts ファイルをインポートできない

``` yml
rules:
  import/extensions:
    - error
    - ts: never
      tsx: never
      js: never
      jsx: never
  react/jsx-filename-extension:
    - error
    - extensions:
      - ".jsx"
      - ".tsx"
settings:
  import/resolver:
    node:
      extensions: [.ts, .tsx, .js, .jsx]
```

## 2.6 設定ファイル（`.eslintrc`）の各プロパティの意味
- 参考：[ESLint の設定ファイル (.eslintrc) の各プロパティの意味を理解する](https://maku.blog/p/j6iu7it/)

# 3. Prettierの設定
## 3.1 Prettierとは
- コードフォーマッター
- 一番の特徴は**Opinionated（独断的な）** コードフォーマッター
  - ユーザーに自由なカスタマイズを許さずPrettier 自身が定義しているスタイルに強制的にフォーマットする（セミコロンの有無など最低限の設定はできる）
  - これによりコーディングスタイルに関する 不毛な議論を避けることができプロジェクト内のコーディングスタイルを簡単に統一することができる
- Prettier はあくまでコードの**フォーマットのみを行う**
  - **静的解析は行わない。**
  - コードの意味を解析して危険な部分（潜在的バグ）を検出してくれたりはしないので、そういったことを行いたい場合は、他の静的解析ツール（ESLint など）を使う必要がある
  - 「Prettier による整形 ＋ ESLint による静的解析」という形で組み合わせて使うのが一般的です。

## 3.2 インストール
- `npm install prettier -D`
- 設定ファイル（`.prettierrc`）の作成
  - 他のツール（VS Code など）に、このプロジェクトが Prettier を使用していることを知らせるために、設定ファイル（`.prettierrc.json` や `.prettierrc.yml`）を作成しておく。
  -  特別な設定をしないのであれば、設定内容は空っぽで構わない。（JSON 形式であれば {}、YAML 形式であれば本当に何も書かないでで OK）。

## 3.3 Prettierの実施
- `$ npx prettier main.ts`
  - prettier コマンドにソースコードを食わせると、Perttier のスタイルに従ってフォーマットし直した結果を標準出力に出力してくれます。
- `$ npx prettier main.ts -w`
  - `-w` (`--write`) オプションを付けて実行すると、フォーマット結果をそのファイルに書き戻します。
-  ディレクトリ名や グロブパターン で複数ファイルをまとめて処理できます。

### 実施例
- カレントディレクトリ以下のファイルを整形
  - `$ npx prettier --write .`
- src ディレクトリ以下のファイルを整形
  - `$ npx prettier --write src`
- src ディレクトリ以下の .ts、.tsx ファイルを整形
  - `$ npx prettier --write src/**/*.{ts,tsx}`


カレントディレクトリ以下のファイルをまとめて整形する場合は、先にどのファイルが整形対象になっているかを調べておくと安心です。 `-l (--list-different)` オプション、あるいは `-c (--check)` オプションを付けて実行すると、Prettier のフォーマットに従っていないファイルを一覧表示できます。

- カレントディレクトリ以下のファイルで整形対象になるものを確認
  - `$ npx prettier -l .`

## 3.4 スクリプト化
毎回 npx prettier ... と入力するのは面倒なので、npm スクリプト化しておきます。

package.json（抜粋）
``` json
{
  "scripts": {
    "lint:prettier": "prettier --check src",
    "fix:prettier": "prettier --write src",
```

これで、次のように簡単に Prettier によるフォーマットをかけられるようになります。

`$ npm run lint:prettier  # 違反のチェックだけしたいとき`
`$ npm run fix:prettier   # 自動で fix 実行`

npm スクリプト名は lint、fix のようなシンプルな名前にしてもよいのですが、ここでは ESLint も導入することを考えて、詳細な名前を付けるようにしています（ESLint 側のスクリプトには lint:eslint、fix:eslint という名前を付ける想定）。

 ## 3.5 Prettierのカスタマイズ
Prettier のフォーマット方法は、.prettier.{json,yml,js} ファイルである程度カスタマイズできますが、Prettier はフォーマット関連のオプションをほとんど用意しておらず、可能な限りデフォルト設定のまま使うべきとされています。 なぜなら、スタイル設定による不毛な議論を防ぐことを一番の目的としているからです（参考: Prettier のオプションに対する思想）。 過去の経緯で追加されてしまったオプションは、今さら消すことができないという理由で残っているものがあり、これらも通常使うべきではありません。
Prettier のデフォルトスタイルは十分に成熟したとし、今後はフォーマット関連のオプションは追加しないとしています。 そんな中でもいくつかのオプションは使われることがあるので、下記にいくつか紹介しておきます。

### printWidth (default: 80)
一行あたりの文字数がどれくらいであるべきかを指定します。ESLint の max-len（最大文字数）とは若干概念が異なり、実際にはこの値よりも長い行が出力されることはあります。各種フォーマッターで、最大文字数の設定を 100 や 120 にしているプロジェクトは多くありますが、Prettier は printWidth はあくまでデフォルトの 80 を使うことを推奨しています。80 文字を超える文字列リテラルや、深いネストによって 80 文字を超える場合は、Prettier はそのまま出力します。

### semi (default: true)
行末のセミコロンの有無を指定します。デフォルトではセミコロンが付加されますが、JavaScript Standard Style ではセミコロンを省略する提案がされていますし、Next.js の create-next-app コマンドで出力される雛形コードもセミコロンなしのコードになっていたりします。将来的にセミコロンなしが主流になる可能性は十分にあります。

### singleQuote (default: false)
JSX 以外でダブルクォートの代わりにシングルクォートを使用
文字列リテラルはデフォルトでダブルクォートで囲まれます。シングルクォートで囲みたいときは singleQuote オプションを true に設定します。多くのスタイルではシングルクォートが優先されているので、この設定だけは true にして使う人が多いかもしれません。ちなみに、この設定を true にしても、JSX コード内の文字列リテラルはダブルクォートで囲まれます（jsxSingleQuote という別オプションになっています）。

### jsxSingleQuote
JSX でダブルクォートの代わりにシングルクォートを使用

### tralingComma (default: “es5”)
デフォルトでは、配列などの末尾要素の後にカンマ (,) を付加されます。"none" にするとカンマが付かなくなります。

.prettierrc の記述例（YAML形式）
``` yml
printWidth: 100
semi: false
singleQuote: true
trailingComma: none
```


# 4. ESLintとPrettierの併用方法
## 結論
- コードフォーマットは Prettier で行う
- コード品質のチェックは ESLint で行う
- ESLint が持っているコードフォーマットのルールは eslint-config-prettier で off にする
- その他の連携ツールは使用しない (コードフォーマット(Prettier)とコード品質のチェック(ESLint)はそれぞれ別のものとして実行する)

## 解説
プロジェクトに ESLint を導入 している場合、Prettier によるフォーマットと ESLint による解析ルールが競合するので、その部分を無効にしておく必要があります。 これを簡単に行ってくれるのが、`eslint-config-prettier` パッケージ（ESLint プラグイン）です。 このパッケージは Prettier チームが正式に提供している ものなので、誰かが適当に作ったパッケージではなく、これを使うことをお勧めします。

- npm の場合
  - `$ npm install eslint-config-prettier -D`
  - あとは、ESLint の設定ファイルの extends プロパティの最後に `prettier` というコンフィグを追加するだけで OK です。

.eslintrc.yml（抜粋）
``` yml
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
```

# 5. `package.json` の設定
## 5.1 npm-run-all のインストール
- `npm run`コマンドのデフォルトでは、複数の NPM スクリプトを連続して実行する方法（Linux の cmd1 && cmd1）や、並列に実行する方法（Linux の cmd1 & cmd2）は提供されていません。 強引に各 OS のシェルの && や & を組み合わせることでできないことはありませんが、Windows と Linux で記述方法が異なるので、OS に依存した package.json になってしまいます。
- このような場合に、`npm-run-all` という NPM パッケージを使用すると、複数の NPM スクリプトを逐次／並列実行するスクリプトを、OS に依存しない形で記述できるようになります。
### インストール
- `$ npm install -D npm-run-all`

### 実行の種類
- シーケンシャル実行 (`run-s`)
- パラレル実行 (`run-p`)
- [公式：コマンドの詳細](https://github.com/mysticatea/npm-run-all/blob/HEAD/docs/npm-run-all.md)

## 5.2 npm scriptsの構成
npm scripts の構成は、[Prettier 本体プロジェクトの pacakge.json](https://github.com/prettier/prettier/blob/cc1f0543e6fd5cf09fd82c25b393124aa5ef55ad/package.json#L148-L158) を参考にする

``` json
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "lint": "run-p -l -c --aggregate-output lint:*",
    "lint:eslint": "eslint .",
    "lint:prettier": "prettier --check .",
    "fix": "run-s fix:prettier fix:eslint",
    "fix:eslint": "npm run lint:eslint -- --fix",
    "fix:prettier": "npm run lint:prettier -- --write"
  },
```

# 6. 保存時の自動フォーマット（VSCode利用）
## 設定手順

1. VSCode の settings.json を開く
1. 開いた settings.json に自動フォーマット設定を追記します。

``` json
{
  // formatter
  "editor.formatOnSave": true, // ファイル保存時の自動フォーマット有効
  "editor.formatOnPaste": true, // ペーストした文字の自動フォーマット有効
  "editor.formatOnType": true, // 文字入力行の自動フォーマット有効
  "editor.defaultFormatter": "esbenp.prettier-vscode", // デフォルトフォーマッターをPrettierに指定
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true // ファイル保存時に ESLint でフォーマット
  },
}
```
ここで`eslint.format.enable`をtrueに設定するとeslintによるformatが動いてしまうのでNG

# 7. husky, lint-staged の設定
## 参考
- [Next.js11にhuskyを導入する -Qiita](https://qiita.com/dtakkiy/items/8d6025c052784ab8eef4)
- [husky公式](https://www.npmjs.com/package/husky)

## 7.1 lint-stagedとは
- int-staged は Git に stage されているファイル (コミット対象のファイル) に指定したスクリプトを実行するツール
- コミット対象のファイルにのみ Lint などのスクリプトを実行して時間を節約しましょう、というのが lint-staged のコンセプト

### 7.1.1 インストール
- `npm install -D lint-staged`

### 7.1.2 package.json
package.jsonには、ステージングファイルに対して、対象ファイルと実行するコマンドを追加します。
注意：`npm-run-all`を利用したスクリプトは利用できない
例：上記で設定している `"fix": "run-s fix:prettier fix:eslint",` などを実行するとエラーになってします

``` json
  "lint-staged": {
    "*.{js,jsx,ts,tsx}": [
      "npm run lint:eslint",
      "npm run lint:prettier"
    ]
  },
```

## 7.2 husky
### 7.2.1 概要
- husky とは Git hooks が簡単にできるnpmパッケージ
- Git hooks とは、コミットやプッシュなど、特定のアクションが発生したとき、特定のスクリプトを実行する仕組み
- git hook を使うためには`.git/hooks`ディレクトリ内にスクリプトを書く必要がありますが、husky を使うともっと楽に git hook を制御することができます。

### 7.2.2 インストール
- `npm install -D husky`

### 7.2.3 設定
package.jsonに`prepare`キーを追加します。
`prepare`は、npm installで全てのインストールが終了した後に実行されるコマンド(npmのコマンド)
- `npm set-script prepare "husky install"`

`husky install` コマンドを実行し、huskyの設定ファイル（`.husky`ファイル）をプロジェクトに追加する
- `npm run prepare`

下記のコマンドを実行すると`.husky/pre-commit`ファイルが作成されます。
`npx husky add .husky/pre-commit "npx lint-staged"`

```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged

// もしtestを実行したい場合は、以下のように追記します。
test
```

# 参考
https://zenn.dev/t28_tatsuya/articles/integration-of-eslint-and-prettier
https://zenn.dev/teppeis/articles/2021-02-eslint-prettier-vscode
https://zenn.dev/standard_soft/articles/cc0b3ee4d24239
https://github.com/prettier/eslint-config-prettier#installation
https://maku77.github.io/nodejs/npm/npm-run-all.html
https://maku.blog/p/yfow6dk/
