### ISSUE TITLE
Jenkins

### ISSUE THREAD

**Issue by Haramaki0326** [Haramaki0326/StudyToDo#83]

**Comment by Haramaki0326** [comment]
# JenkinsをLinux（WSL2）上にたて、Windows端末をAgent（Slave）として登録するやり方のメモ

## 参考サイト
- [Docker ComposeでローカルにサクッとJenkinsを構築する](https://amateur-engineer-blog.com/jenkins-docker/)
- [Vagrant環境のDockerでJenkinsサーバを構築し、スレーブのWindowsマシンを接続する(後半)](https://qiita.com/masatomix/items/6d751d361af760346383)

## やり方
- slave（Windows）側でコマンドプロンプトを管理者権限で立ち上げ、`agent.jar`を実行しておいてやることで、master(Linux)側と通信ができるようになる
    - `java -jar agent.jar -jnlpUrl http://172.24.0.1:8080/computer/WindowsPC/jenkins-agent.jnlp -secret 6366f7c08e83d36f5fb7f86d8a79c3f8e1ff54634305bb83248244709a05d2c2 -workDir "C:\jenkins_slave"`

## 注意点
- Javaは最新のものをダウンロードしておくこと
    - [Oracleのダウンロード](https://www.oracle.com/java/technologies/downloads/#jdk18-windows)
- コマンドプロンプトで`agent.jar`を呼び出す際の注意点
    - コマンドプロンプトを管理者権限で開くこと
    - agent.jarを置いたディレクトリ c:/temp で実行すること
    - URLを localhostではなく、WindowsPCから見たときのJenkinsサーバのIP(ようするにブラウザバーに表示されているIPのこと) にすること
- 50000ポートを開いておかないとエラーになるので注意
    - `serious: http://192.168.10.136:8080/provided port:50000 is not reachable`
    - docker-composeファイルで50000ポートをあけとくこと

## docker-compose.yml
``` yml
version: "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:latest
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
```
